sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t andreta/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andreta/react-test npm test -- --coverage

after_success:
  - docker build -t andreta/multi-client ./client
  - docker build -t andreta/multi-nginx ./nginx
  - docker build -t andreta/multi-server ./server
  - docker build -t andreta/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push andreta/multi-client
  - docker push andreta/multi-nginx
  - docker push andreta/multi-server
  - docker push andreta/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-428441761464"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
